version: 2
jobs:
  build&lint:
    working_directory: ~/circleci-test-back
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: |
            npm i
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - 'node_modules'
      - run:
          name: Lint
          command: |
            npm run lint
      - run:
          name: Build
          command: |
            npm run build